### ISSUE TITLE
how to use pip ?

### ISSUE THREAD

**Issue by H-TWINKLE** [jixunmoe/py3-win7#1]
how to use pip ?

**Comment by jixunmoe** [comment]
Use `python -m pip`.

e.g. `python -m pip install requests`

**Comment by H-TWINKLE** [comment]
hi, i use python -m pip fail,alert no module 
C:\Program Files\Python311\python.exe: No module named pip
![图片](https://github.com/jixunmoe/py3-win7/assets/34811911/59f3440d-1087-46e6-ad46-4ead51425f50)

it`s my install pic and in Scripts dir ,not found pip.exe file
![图片](https://github.com/jixunmoe/py3-win7/assets/34811911/87427906-ee49-4390-9d3a-9bf15d63dd31)

when i chose precompile standard libaray, python3.11 not install success.
![图片](https://github.com/jixunmoe/py3-win7/assets/34811911/6740bfcb-63be-48d5-879c-cd556bfae87a)
![图片](https://github.com/jixunmoe/py3-win7/assets/34811911/1d1d5f80-3730-4db8-9381-ff0e717f4c81)

**Comment by H-TWINKLE** [comment]
when i choose precompile standard libaray ,it will wait  wait  wait
![图片](https://github.com/jixunmoe/py3-win7/assets/34811911/b302aafb-e383-45a5-8b4e-614723ac8a89)

**Comment by jixunmoe** [comment]
Weird, but you can try install it manually with pip installer (pip.py).

https://pip.pypa.io/en/stable/installation/#get-pip-py

Try running the pip installer with the python.exe you just installed.

**Comment by jixunmoe** [comment]
Previously I tested against Python 3.11.4 installer with pip checked, you may have a better luck with that specific version.

**Comment by H-TWINKLE** [comment]
> Previously I tested against Python 3.11.4 installer with pip checked, you may have a better luck with that specific version.

I installed it using a virtual machine in win7sp1.
 Maybe I still lack the win7 system patch, thank you.
